-- ==============================================================================
-- VeriScale Database Schema: Products, Variants, Transactions & RLS Policies
-- ==============================================================================

-- 1. Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 2. Products Table (Master Goods & Stock)
create table if not exists public.products (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    name text not null,
    stock numeric not null default 0,
    unit_label text default 'Units',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Products
alter table public.products enable row level security;

create policy "Users can view their own products"
    on public.products for select
    using (auth.uid() = user_id);

create policy "Users can insert their own products"
    on public.products for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own products"
    on public.products for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "Users can delete their own products"
    on public.products for delete
    using (auth.uid() = user_id);

-- 3. Product Variants Table (Sold Portions, Prices & Stock Multipliers)
create table if not exists public.product_variants (
    id uuid default gen_random_uuid() primary key,
    product_id uuid references public.products(id) on delete cascade not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    unit_name text not null,
    cost_price numeric not null default 0,
    selling_price numeric not null default 0,
    stock_equivalent numeric not null default 1.0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Product Variants
alter table public.product_variants enable row level security;

create policy "Users can view their own product variants"
    on public.product_variants for select
    using (auth.uid() = user_id);

create policy "Users can insert their own product variants"
    on public.product_variants for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own product variants"
    on public.product_variants for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "Users can delete their own product variants"
    on public.product_variants for delete
    using (auth.uid() = user_id);

-- 4. Transactions Table (Sales Records with Product/Variant metadata)
create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    product_id uuid references public.products(id) on delete set null,
    product_name text,
    variant_name text,
    quantity numeric default 1,
    unit_price numeric default 0,
    cost_price numeric default 0,
    items text not null default '',
    total_amount numeric not null default 0,
    total_profit numeric not null default 0,
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- If table already existed, add new columns if missing
alter table public.transactions add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.transactions add column if not exists product_id uuid references public.products(id) on delete set null;
alter table public.transactions add column if not exists product_name text;
alter table public.transactions add column if not exists variant_name text;
alter table public.transactions add column if not exists quantity numeric default 1;
alter table public.transactions add column if not exists unit_price numeric default 0;
alter table public.transactions add column if not exists cost_price numeric default 0;

-- Enable RLS for Transactions
alter table public.transactions enable row level security;

create policy "Users can view their own transactions"
    on public.transactions for select
    using (auth.uid() = user_id);

create policy "Users can insert their own transactions"
    on public.transactions for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own transactions"
    on public.transactions for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "Users can delete their own transactions"
    on public.transactions for delete
    using (auth.uid() = user_id);

-- 5. Performance Indexes
create index if not exists idx_products_user on public.products(user_id);
create index if not exists idx_product_variants_product on public.product_variants(product_id);
create index if not exists idx_product_variants_user on public.product_variants(user_id);
create index if not exists idx_transactions_user on public.transactions(user_id);
create index if not exists idx_transactions_date on public.transactions(date desc);
